#pragma once

inline constexpr char* CUSTOM_EVENTS = "CUSTOM_EVENTS";

enum CUSTOM_EVENTS_ENUM
{
    CREDENTIALS_AQUIRED,
    SCAN_AVAILABLE_APS,
    SEND_DEFAULT_PARAMETERS,
    CUSTOM_PARAMETERS_RECEIVED
};